// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220419025631_Migracion4")]
    partial class Migracion4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Backend.Models.AgendaTelefonica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("contactosId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("empresasnit")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idContacto")
                        .HasColumnType("int");

                    b.Property<int>("idEmpresa")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("contactosId");

                    b.HasIndex("empresasnit");

                    b.ToTable("AgendaTelefonica");
                });

            modelBuilder.Entity("Backend.Models.Contacto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar=100");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar=9");

                    b.HasKey("Id");

                    b.ToTable("Contacto");
                });

            modelBuilder.Entity("Backend.Models.Empresa", b =>
                {
                    b.Property<string>("nit")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar=9");

                    b.Property<string>("Nrc")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar=17");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar=100");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar=150");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar=100");

                    b.Property<int>("perfilid")
                        .HasColumnType("int");

                    b.Property<string>("representante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar=100");

                    b.Property<int?>("rubro")
                        .IsRequired()
                        .HasColumnType("varchar=100");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar=9");

                    b.Property<string>("telefonoMovil")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar=9");

                    b.Property<int?>("tipoEmpresaid")
                        .HasColumnType("int");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar=100");

                    b.HasKey("nit");

                    b.HasIndex("perfilid");

                    b.HasIndex("tipoEmpresaid");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Backend.Models.Perfil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("calificacion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar=1");

                    b.Property<string>("escrituras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar=100");

                    b.Property<string>("razonSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar=100");

                    b.Property<bool>("sucursal")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("Backend.Models.TipoEmpresa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("tipo")
                        .HasColumnType("varchar=100");

                    b.HasKey("id");

                    b.ToTable("TipoEmpresa");
                });

            modelBuilder.Entity("Backend.Models.AgendaTelefonica", b =>
                {
                    b.HasOne("Backend.Models.Contacto", "contactos")
                        .WithMany("agendaTelefonica")
                        .HasForeignKey("contactosId");

                    b.HasOne("Backend.Models.Empresa", "empresas")
                        .WithMany("agendaTelefonica")
                        .HasForeignKey("empresasnit");

                    b.Navigation("contactos");

                    b.Navigation("empresas");
                });

            modelBuilder.Entity("Backend.Models.Empresa", b =>
                {
                    b.HasOne("Backend.Models.Perfil", "perfil")
                        .WithMany()
                        .HasForeignKey("perfilid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.TipoEmpresa", "tipoEmpresa")
                        .WithMany()
                        .HasForeignKey("tipoEmpresaid");

                    b.Navigation("perfil");

                    b.Navigation("tipoEmpresa");
                });

            modelBuilder.Entity("Backend.Models.Contacto", b =>
                {
                    b.Navigation("agendaTelefonica");
                });

            modelBuilder.Entity("Backend.Models.Empresa", b =>
                {
                    b.Navigation("agendaTelefonica");
                });
#pragma warning restore 612, 618
        }
    }
}
